DBMS/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^movies/', include('movies.urls')),
)

if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'media/(?P<path>.*)',
                'serve',
                {'document_root': settings.MEDIA_ROOT}), )

# /usr/local/lib/python2.7/dist-packages/django/contrib/auth/views.py
# Anita  (amit) ----   +919829356969
# J@home (Jatin) ----- 07820834476
# m...  ---------- +919667370614
# khelu(Kanav) ---------- +918952882438

movies/urls.py
from django.conf.urls import *
from movies import views
from django.conf import settings

urlpatterns = patterns('',
       url(r'^$', views.home, name='home'),
       url(r'^register/$',views.register,name='register'),
       url(r'^login/$',views.login,name = 'login'),
       url(r'^view_all_message/$',views.view_all_message ,name = 'view_message'),
       url(r'^message/(?P<name>\w+)/$',views.view_user_message ,name = 'user_message'),
       url(r'^message/$',views.save_message ,name = 'message'),
       url(r'^latest_updates/$',views.latest_updates, name = 'updates'),
       url(r'^profile/(?P<name>\w+)/$',views.Profile,name='profile'),
       url(r'^logout/$', views.logout, name="logout"),
       url(r'^add/$', views.add, name='add'),
       url(r'^get/$', views.get, name='get'),
       url(r'^follow/$', views.follow, name='follow'),
       url(r'^unfollow/$', views.unfollow, name='unfollow'),
       url(r'^remove_picture/$', views.no_picture, name='no_picture'),
       url(r'^changed/$', views.change_profile, name='change'),
       url(r'^facebook_profile/$', views.facebook_profile, name='facebook_profile'),
       url(r'^suggestion/$', views.suggestion, name='suggestion'),
       url(r'^user/$', views.user, name='user'),
       url(r'^reset/(?P<reset>\w+)/$', views.reset, name='reset'),
	   url(r'^transaction/$', views.trans, name='trans'),
	   url(r'^final/(?P<transid>\w+)/$', views.final, name='final'),
	   url(r'^sell/(?P<transid>\w+)/$', views.transaction, name='transaction'),
       url(r'^view/(?P<top>\w+)/$', views.top100, name='top'),
       url(r'^comment/post/(?P<movieid>\w+)/$', views.post_comment, name='post'),
       url(r'^comment/edit_history/$', views.edit_comment_history, name='history'),
       url(r'^comment/comment/$', views.do_comment, name='comment'),
       url(r'^comment/edit/$', views.edit_comment, name='edit'),
       url(r'^comment/like/$', views.like_comment, name='like'),
       url(r'^comment/unlike/$', views.unlike_comment, name='unlike'),
       url(r'^comment/show_likes/$', views.show_liked_people, name='show_like'),
       url(r'^comment/delete/$', views.delete_comment, name='delete'),
	   url(r'^director/(?P<director>[A-Z a-z . _ -]+)/$', views.director, name='director'),
	   url(r'^actor/(?P<actor>[A-Z a-z . _ -]+)/$', views.actor, name='actor'),
	   url(r'^genre/(?P<genre>[A-Z a-z . _ -]+)/$', views.genre, name='genre'),
	   url(r'^rate/(?P<movieid>\w+)/$',views.update, name='update'),
       url(r'^sure/password/reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/movies/password/reset/done/'}, name="password_reset"),
       url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
       url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',{'post_reset_redirect' : '/movies/sure/password/done/'}),
       url(r'^sure/password/done/$', 'django.contrib.auth.views.password_reset_complete'),
	   url(r'^(?P<movieid>\w+)/$', views.movies, name='movie'),
       url(r'^(?P<name>\w+)/(?P<follow>\w+)/$', views.display_follow, name='display_follow'),
)

if settings.DEBUG:
        urlpatterns += patterns(
                'django.views.static',
                (r'media/(?P<path>.*)',
                'serve',
                {'document_root': settings.MEDIA_ROOT}), )

movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
#   sudo fuser -k 8000/tcp

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	sex = models.CharField(max_length=8)
	age = models.IntegerField(default=0)
	occupation = models.CharField(max_length = 40)
	zipcode = models.CharField(max_length = 20)
	picture = models.ImageField(upload_to='profile_images',blank=True)
	def __unicode__(self):
		return self.user.username

class Change(models.Model):
	picture = models.ImageField(upload_to='profile_images',blank=True)
	def __unicode__(self):
		return self.picture
		
class Follow(models.Model):
	user = models.OneToOneField(User)
	follower = models.ManyToManyField(User,related_name='following',symmetrical=False)
	# user.following.all()
	def __unicode__(self):
		return self.user.username

class Message(models.Model):
	msg = models.TextField(_("Message"))
	sender = models.ForeignKey(User, related_name='sent_messages', verbose_name=_("Sender"))
	recipient = models.ForeignKey(User, related_name='received_messages', null=True, blank=True, verbose_name=_("Recipient"))
	sent_at = models.DateTimeField(_("sent at"), default=timezone.now)
	read_at = models.DateTimeField(_("read at"), null=True, blank=True)
	replied_at = models.DateTimeField(_("replied at"), null=True, blank=True)
	sender_deleted = models.BooleanField(default=False)
	recipient_deleted = models.BooleanField(default=False)

movies/forms.py
from django import forms
from django.contrib.auth.models import User
from movies.models import UserProfile, Change, Message

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ('username','first_name','last_name','email','password')

class UserProfileForm(forms.ModelForm):
	sex = forms.CharField(max_length=8)
	occupation = forms.CharField(max_length=40 )
	zipcode = forms.CharField(max_length=20)
	age = forms.IntegerField()
	class Meta:
		model = UserProfile
		fields = ('sex','age','occupation','zipcode','picture')
	
class LoginForm(forms.ModelForm):
	username = forms.CharField(max_length = 128)
	password = forms.CharField(widget=forms.PasswordInput())		
	class Meta:
		model = User
		fields = ('username','password')
		
class Changed(forms.ModelForm):
	class Meta:
		model = Change
		fields = ('picture',)

movies/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import render_to_response
from django.db import models
from movies.models import UserProfile, Follow, Message
from django.http import HttpResponse as hr, HttpResponseRedirect
from movies.forms import UserForm, UserProfileForm, LoginForm, Changed
from django.core.mail import send_mail
from django.contrib.sites.models import Site
import sys,platform,json,time,random,urllib2,smtplib,unicodedata,psycopg2
import datetime
from django.utils import timezone
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from email.MIMEImage import MIMEImage
from urllib2 import Request
from BeautifulSoup import BeautifulSoup
from time import mktime

class MyEncoder(json.JSONEncoder):
	def default(self, obj):
		if isinstance(obj, datetime.datetime):
			return int(mktime(obj.timetuple()))
		return json.JSONEncoder.default(self, obj)

def home(request):
	context = RequestContext(request)
	context_dict = {}
	if request.user.is_authenticated():
		profile = UserProfile.objects.get(user = request.user)
		context_dict['profile'] = profile
	con = None
	try:
		con = psycopg2.connect(database='project',user='postgres')
		cur = con.cursor()
		cur.execute("SELECT * from movies ORDER BY RANDOM() DESC LIMIT 30")
		ver = cur.fetchall()
		context_dict['ver'] = ver    
	except psycopg2.DatabaseError, e:
		if con:
			con.rollback()
		print 'Error %s' %e
		sys.exit(1)
	finally:
		if con:
			con.close()
	return render_to_response('movies/home.html', context_dict,context)

def change(s):
	for i in range(0,len(s)):
		a = list(s[i])
		a[7] = float(int(a[7]*100))/100
		s[i] = tuple(a) 
	return s
	
def register(request):
	context = RequestContext(request)
	if request.method == 'POST':
		user_form = UserForm(request.POST)
		user_profile = UserProfileForm(request.POST,request.FILES)
		email = request.POST['email']
		name = request.POST['username']
		user_name = User.objects.filter(username = name)
		user_email = User.objects.filter(email = email)
		if (len(user_email)>0 and len(user_name)>0):
			return hr(json.dumps("BOTH"))
		elif (len(user_email)>0):
			return hr(json.dumps("EMAIL"))
		elif (len(user_name)>0):
			return hr(json.dumps("NAME"))
		if user_form.is_valid() and user_profile.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = user_profile.save(commit=False)
			profile.user = user
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
			else:
				profile.picture = "profile_images/default.jpg"	
			profile.save()
			con = None
			try:
				con = psycopg2.connect(database='project',user='postgres')
				cur = con.cursor()
				cur.execute("INSERT INTO user_profile VALUES(%s,%s,%s,%s)", (profile.age,profile.sex,profile.occupation,profile.zipcode,))
				con.commit()
			except psycopg2.DatabaseError, e:
				if con:
					con.rollback()
				print 'Error %s' %e
				sys.exit(1)
			finally:
				if con:
					con.close()
			return hr(json.dumps("NO"))
		else:
			err = json.dumps(user_form.errors)
			return hr(err)
	else:
		if request.user.is_authenticated():
			return HttpResponseRedirect("/movies/profile/"+request.user.username)
		else:
			user_form = UserForm()
			user_profile = UserProfileForm()
	context_dict = { 'user_form': user_form } 
	context_dict['user_profile'] = user_profile
	return render_to_response("movies/register.html",context_dict,context)

@login_required
def no_picture(request):
	if request.user.is_authenticated():
		profile = UserProfile.objects.get(user = request.user)	
		profile.picture = "profile_images/default.jpg"
		profile.save()		
		return hr(json.dumps("NO"))
		
@login_required
def facebook_profile(request):
	if request.method == 'POST':
		if request.user.is_authenticated():
			url = 'https://www.facebook.com/'
			if request.method == 'POST':
				user_id = request.POST['picture']
				req = Request(url + user_id) 
				response = urllib2.urlopen(req)
				the_page = response.read()
				the_page = the_page.replace("<!--", "")
				the_page = the_page.replace("-->", "")
				parsed_html = BeautifulSoup(the_page)
				parsed_things = parsed_html.find('a', {'class':'profilePicThumb'})    			
				pic_url = parsed_things('img')[0]['src']
				facebook_defined = 'https://fbcdn-profile-a.akamaihd.net/'
				splitted_url = pic_url.split('/')
				picture_id = splitted_url[-1].replace('a.', 'n.')
				pic_url = facebook_defined + picture_id
				response = urllib2.urlopen(pic_url)
				pro = request.user.username
				try:
					f = open("/home/vijender/workspace/DBMS/media/profile_images/"+pro+".jpg","wb")
					try:
						f.write(response.read())
					finally:
						f.close()						    	
				except Exception, e:
					raise e			
				profile = UserProfile.objects.get(user = request.user)	
				profile.picture = "profile_images/"+pro+".jpg"				
				profile.save()
				return hr(json.dumps("NO"))	
	else:
		return HttpResponseRedirect("/movies/changed")

@login_required
def change_profile(request):
	context = RequestContext(request)
	if request.method == 'POST':
		profile = UserProfile.objects.get(user = request.user)	
		user_form = Changed(request.FILES)
		if user_form.is_valid():			
			profile = UserProfile.objects.get(user = request.user)	
			profile.picture = request.FILES['picture']				
			profile.save()
			return hr(json.dumps("NO"))
	else:
		change_form = Changed()
		context_dict = {'login_form': change_form }
		return render_to_response("movies/change.html",context_dict,context)		

dict_interest = {0 : "Comedy",1 : "Drama",2 : "Fantasy",3 : "Horror",4 : "Biography",5 : "Thriller",6 : "Crime",7 : "Western",8 : "Musical",9 : "War",10 : "Sci-Fi",11 : "Action",12 : "Documentary",13 : "Romance",14 : "Animation",15 : "Mystery",16 : "Family",17 : "Adventure"}

def make_list(l):
	u = []
	for i in range(len(l)):
		if (l[i] == "yes"):
			u.append(dict_interest[i])
	return u 
			
@login_required		
def latest_updates(request):
	context = RequestContext(request)
	context_dict = {}
	user_suggestion = []
	movies_suggestion = []
	userid = (request.user.id + 943 - 1)
	if request.user.is_authenticated():
		pic = UserProfile.objects.get(user = request.user).picture
		context_dict['pic'] = pic
		try:
			con = psycopg2.connect(database='project',user='postgres')
			cur = con.cursor()
			cur.execute("select interest from movies_userprofile where user_id = %s", (request.user.id,))
			ver = cur.fetchone()
			interest = make_list(ver[0].split(','))
			length = len(interest)
			cur.execute("select count(*) from auth_user");
			count = cur.fetchone()[0]	
			if (length <= 2):
				l = []
				while len(user_suggestion) < 3:
					j = random.randint(2,count-1)
					if (j != 9 and j != request.user.id and j not in l):
						l = l + [j]
						user = User.objects.get(id = j)
						try:
							status = user.follow.follower.filter(username = request.user.username)
						except:
							status = []
						if (len(status) == 0):
							pro = UserProfile.objects.get(user = user)
							user_suggestion.append((pro,user.username,user.first_name,user.last_name))
				l = []
				k = 0
				while len(movies_suggestion) < 3:
					k = k + 1
					j = random.randint(1,1682)
					if (j not in l):
						l = l + [j]
						cur.execute("select count(*) from movies_rated where movieid = %s and userid = %s",(j,userid,))
						current = cur.fetchone()[0]	
						if (current == 0 and k < 50 and length > 0):
							cur.execute("select genre from genre where movieid = %s",(j,))
							res = [row[0] for row in cur.fetchall()]
							if (len(list(set(interest) & set(res))) > 0):
								cur.execute("select title,year,imdbvotes,imdbrating,picture,language,movieid from movies where movieid = %s",(j,))
								result = cur.fetchone()
								a = list(result)
								a[3] = float(int(a[3]*100))/100
								result = tuple(a)
								movies_suggestion.append(result)
								k = 0
						else:
							if (current == 0):
								cur.execute("select title,year,imdbvotes,imdbrating,picture,language,movieid from movies where movieid = %s",(j,))
								result = cur.fetchone()
								a = list(result)
								a[3] = float(int(a[3]*100))/100
								result = tuple(a)
								movies_suggestion.append(result)
								k = 0
			else:
				l = []
				k = 0
				while len(user_suggestion) < 3:
					k = k + 1
					j = random.randint(2,count-1)
					if (j != 9 and j != request.user.id and j not in l):
						l = l + [j]
						cur.execute("select interest from movies_userprofile where user_id = %s", (j,))
						ver = cur.fetchone()
						random_interest = make_list(ver[0].split(','))
						if (k <= 20):
							if (len(list(set(interest) & set(random_interest))) > 2):
								user = User.objects.get(id = j)
								try:
									status = user.follow.follower.filter(username = request.user.username)
								except:
									status = []
								if (len(status) == 0):
									pro = UserProfile.objects.get(user = user)
									user_suggestion.append((pro,user.username,user.first_name,user.last_name))
									k = 0
						else:
							user = User.objects.get(id = j)
							try:
								status = user.follow.follower.filter(username = request.user.username)
							except:
								status = []
							if (len(status) == 0):
								pro = UserProfile.objects.get(user = user)
								user_suggestion.append((pro,user.username,user.first_name,user.last_name))
								k = 0
				l = []
				k = 0
				while len(movies_suggestion) < 3:
					k = k + 1
					j = random.randint(1,1682)
					if (j not in l):
						l = l + [j]
						cur.execute("select genre from genre where movieid = %s",(j,))
						res = [row[0] for row in cur.fetchall()]
						userid = (request.user.id + 943 - 1)

templates/movies/100.html
<!DOCTYPE html>
<html>
{% load static %}	
	<head>
		<title>
			QUERY RESULT
		</title>
		<link href="{% static 'bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'form.css' %}"  rel="stylesheet">
		<link href="{% static 'drag.css' %}"  rel="stylesheet">
		<style>
			body {
				margin-top: 60px;
			}
			#abhi{
				margin-left: 10px;
				float:left
			}
		</style>	
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
					<ul class="nav navbar-nav pull-left">
						<li class="dropdown" style="margin-left : -50px">
							<ul class="nav navbar-nav pull-left">
								<li class="dropdown"> 
									<a href="/movies/">HOME PAGE</a>
								</li>
								<li>
									<a href="/movies/add/">ADVANCED SEARCH</a>
								</li>	
								<li>
									<a href="/movies/view/top100/">DIRECTOR's CUT TOP 100</a>
								</li>
								<li>
									<a href="/movies/view/bottom100/">DIRECTOR's CUT BOTTOM 100</a>
								</li>
							</ul>
						</li>
					</ul>
				{% if user.is_authenticated %}
					<ul class="nav navbar-nav pull-left" style="margin-left : 32px">
						<li class="dropdown">
							<img src = "/home/vijender/workspace/DBMS/media/{{ profile.picture }}" width="60" height="60" />
						</li>
						<li style="margin-left : 10px">
							<a href="/movies/profile/{{ user.username }}">VIEW PROFILE</a>
						</li>
						<li style="margin-left : -10px">
							<a href="/movies/latest_updates/">VIEW UPDATES</a>
						</li>
						<ul class="nav navbar-nav pull-left" id = "menu">
							<li style="padding : 0px 10px 30px 5px" class="dropdown">OPTIONS <b class="caret"></b>
								<ul class = "sub-menu">
									<div class="list-group" style="background-color : white; overflow-y : auto; width : 200px; position : absolute; top : 38px; left : -110px">
										<a href="/movies/reset/password"><div class="list-group-item"><li>Change Password</li></div></a>
										<a href="/movies/reset/profile"><div class="list-group-item"><li>Update Profile</li></div></a>
										<a href="/movies/logout/"><div class="list-group-item"><li>Logout</li></div></a>
									</div>
								</ul>
							</li>
						</ul>
					</ul>
				{% else %}
					<ul class="nav navbar-nav pull-right">
						<li class="dropdown">
							<ul class="nav navbar-nav pull-right">
								<li class="dropdown"> 
									<a href="/movies/login">Sign In</a>
								</li>
								<li>
									<a href="/movies/register/">Sign Up</a>
								</li>		
							</ul>
						</li>
					</ul>
				{% endif %}
			</div>
		</nav>
		<div style="width:1020px; margin-top:100px; margin-left:auto; margin-right:auto; ">
			<div id="header" style="background-color: #7E79AC ;">
				<h2 style="margin-bottom:0;">{{ top }} DIRECTOR's CUT MOVIES</h2>
			</div>	
		{% for act in movie %}
			<div  style="background-color:#FFD700;height:104px;width:300px;float:left;">
				<a href="/movies/{{ act.10 }}"><img src = "/home/vijender/workspace/DBMS/media/{{ act.9 }}" width="100" height="100" /></a> 
			</div>
			<div id="menu" style="background-color:#FFD700;  height:104px; width:400px; float:left;">
				<a href="/movies/{{ act.10 }}"><b>{{ act.0 }}({{ act.1 }}) </b></a> 
			</div> 
			<div id="menu" style="background-color:#FFD700;height:104px; width:160px; float:left;">
					<b>{% if act.7 < 0 %} N/A {% else %} {{ act.7 }} {% endif %}</b>
			</div> 
			<div id="menu" style="background-color:#FFD700;height:104px; width:160px; float:left;">
					<b>{% if act.8 < 0 %} N/A {% else %} {{ act.8 }} {% endif %}</b>
			</div> 
		{% endfor %}
	</body>
</html>

templates/movies/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>		
		<link href="{% static 'bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'form.css' %}"  rel="stylesheet">
		<script src="{%static 'jquery.js' %}"></script>
		<script src="{%static 'forms.js' %}"></script>
		<script>
			$(document).ready(function(){
				var check = false;
				$("#user_form").ajaxForm(function(data){
					if ($.parseJSON(data) == "NO") {
						alert("Registered Successfully,\n login to view your profile");
						window.location.href = 'http://127.0.0.1:8000/movies/login/';
					}
					else if ($.parseJSON(data) == "EMAIL"){
						$("#mail").html("<b>This E-Mail has already been registered.</b>");
						$("#mail").show();
					}
					else if ($.parseJSON(data) == "NAME"){
						$("#user").html("<b>User with this Username already exists.</b>");
						$("#user").show();
					}
					else if ($.parseJSON(data) == "BOTH"){
						$("#mail").html("<b>This E-Mail has already been registered.</b>");
						$("#user").html("<b>User with this Username already exists.</b>");
						$("#mail").show();
						$("#user").show();
					}
					else {
						$.each($.parseJSON(data), function(idx,obj){
							$("#user").html("<b>"+obj+"</b>");
							$("#user").show();
						})
					}
				})
				$("#sub").click(function(e){
					var status = "YES";
					var username = $("#id_username").val();
					var password = $("#id_password").val();
					var email = $("#id_email").val();
					var sex = $("input[name=sex]:radio:checked").val();
					var age = $("#id_age").val();
					var first = $("#id_first_name").val();
					var last = $("#id_last_name").val();
					var occupation = $("#id_occupation").val();
					var zipcode = $("#id_zipcode").val();
					if (username == "" || password == "" || first == "" || last == "" || email == "" || !sex || age == "" || age != "" || occupation == "" || zipcode == ""){
						if (username == "") {
							$("#user").html("<b>This Field is Required</b>");
							$("#user").show();
							status = "NO";
						}
						if (password == "")	{
							$("#pass").show();
							status = "NO";	
						}
						if (email == "") {
							$("#mail").show();
							status = "NO";
						}
						if (first == ""){
							$("#first").show();
							status = "NO";
						}
						if (last == ""){
							$("#last").show();
							status = "NO";
						}
						if (!sex){
							$("#sexy").show();
							status = "NO";
						}
						if (age==""){
							$("#age").html("<b>This Field is Required</b>");
							$("#age").show();
							status = "NO";
						}
						if (occupation==""){
							$("#occ").show();
							status = "NO";
						}
						if (zipcode==""){
							$("#zip").show();
							status = "NO";
						}
						if (age != "") {
							for (i=0; i<age.length; i++){
								var c = age.charAt(i).charCodeAt(0);
								if(c <48 || c >57){
									$("#age").html("<b>Age Must Be Numerical</b>");
									$("#age").show();
									break;
								}
							}
							if (i != age.length) {
								status = "NO";
							}
						}
						if (status == "NO") return false;
						else return true;
					}
				})
				$("#user_form").keyup(function(){
					$("#user").hide(); $("#pass").hide(); $("#mail").hide();  $("#sexy").hide();
					$("#zip").hide(); $("#age").hide(); $("#occ").hide();  $("#first").hide(); $("#last").hide(); 
				})
			})
		</script>
		<style>
			body {
				margin-top: 60px;
			}
			span{
				display: inline-block;
			}
			#big-form li{
				margin-left : 100px; 
				color: red;
			}
		</style>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
					<ul class="nav navbar-nav pull-left">
						<li class="dropdown">
							<ul class="nav navbar-nav pull-right">
								<li class="dropdown"> 
									<a  href="/movies/">HOME PAGE</a>
								</li>
								<li>
									<a href="/movies/add/">ADVANCED SEARCH</a>
								</li>
								<li>
									<a href="/movies/view/top100/">DIRECTOR's CUT TOP 100</a>
								</li>
								<li>
									<a href="/movies/view/bottom100/">DIRECTOR's CUT BOTTOM 100</a>
								</li>		
							</ul>
						</li>
					</ul>
			</div>
		</nav>
			<h1 class="text-center" style="color : white"> REGISTER HERE </h1>
			    <div style="width : 500px; margin-left : 400px" id="big-form" class="well auth-box">
					<form id="user_form" method="post" action="/movies/register/" enctype="multipart/form-data">
						{% csrf_token %}
						<fieldset>
							<legend>Sign Up</legend>
							<div class="form-group">
								<label class=" control-label" for="textinput">  
									Username: <span style="margin-left : 10px">{{ user_form.username }}</span><br>
									<li id="user" hidden></li>
									Password: <span style="margin-top : 20px; margin-left : 15px; ">{{ user_form.password }}</span><br>
									<li id="pass" hidden><b>This Field is Required</b></li>
									First Name: <span style="margin-top : 20px; margin-left : 2px; ">{{ user_form.first_name }}</span><br>
									<li id="first" hidden><b>This Field is Required</b></li>
									Last Name: <span style="margin-top : 20px; margin-left : 8px; ">{{ user_form.last_name }}</span><br>
									<li id="last" hidden><b>This Field is Required</b></li>
									E-Mail ID: <span style="margin-top : 20px; margin-left : 20px">{{ user_form.email }}</span><br>
									<li id="mail" hidden><b>This Field is Required</b></li>
									Sex: <span style="margin-top : 20px; margin-left : 82px"> 
											<input type="radio" name="sex" id="male" value="male">
											<label for="male">Male</label>
											<input style="margin-left : 42px" type="radio" name="sex" id="female" value="female">
											<label for="female">Female</label>
										</span><br>
									<li id="sexy" hidden><b>This Field is Required</b></li>
									Age: <span style="margin-top : 20px; margin-left : 60px">{{ user_profile.age }}</span><br>
									<li id="age" hidden></li>
									Occupation: <span style="margin-top : 20px; margin-left : 3px">{{ user_profile.occupation }}</span><br>
									<li id="occ" hidden><b>This Field is Required</b></li>
									Zipcode: <span style="margin-top : 20px; margin-left : 29px">{{ user_profile.zipcode }}</span><br>
									<li id="zip" hidden><b>This Field is Required</b></li>
									Image: <span style="margin-top : 20px; margin-left : 43px">{{ user_profile.picture }}</span><br>
								</label>
							</div>
							<input id="sub" type="submit" name="submit" value="Register" />
						</fieldset>
					</form>
    </body>
</html>